### ISSUE TITLE
Errors while running rpvg

### ISSUE THREAD

**Issue by prenderj** [jonassibbesen/rpvg#33]
Hi

I have been trying to run the rpvg example but unfortunately keep getting errors. If I compile from source or use the docker container with singularity I get this error:

```
$ ../../Progs/rpvg/bin/rpvg -t 4 -g graph.xg -p pantranscriptome.gbwt -f pantranscriptome.txt.gz -a mpmap_align.gamp -o rpvg --inference-model haplotype-transcripts
Running rpvg (commit: 0380bdb172bbe255a18ed070935fa0013dc02548)
Random number generator seed: 1646476787
terminate called after throwing an instance of 'std::runtime_error'
  what():  [io::ProtobufIterator] could not parse message
Aborted
```

If try to use the docker container directly I get this one:

```
$ docker run quay.io/jsibbesen/rpvg rpvg -t 4 -g graph.xg -p pantranscriptome.gbwt -f pantranscriptome.txt.gz -a mpmap_align.gamp -o rpvg --inference-model haplotype-transcripts
Running rpvg (commit: 0380bdb172bbe255a18ed070935fa0013dc02548)
Random number generator seed: 1646476861
rpvg: /home/rpvg/src/main.cpp:512: int main(int, char**): Assertion `frag_alignments_istream.is_open()' failed.
```

Any help would be great.

Thanks
James

**Comment by George-du** [comment]
Hi, James
      Can you give me some advice on how to install the software through the source code? I encountered a series of error messages, like this https://github.com/jonassibbesen/rpvg/issues/32.
Thanks
Du

**Comment by George-du** [comment]
Hi, James
       
       Is there any progress on this issue?

       If I try to use the singularity container:

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/26595839/157207201-4662acec-e820-4136-9b5c-f72dc693ea9b.png">

      Besides, If I try to use the docker container with "-m" and "-d" option:

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/26595839/157206755-e685e148-711e-4a1f-b682-cb55777b3c7f.png">

Thanks
Du

**Comment by jonassibbesen** [comment]
Hi James and Du,

Thanks for writing. I am looking into this now. Will try to see if I can replicate the errors you shared. 

Best,

Jonas

**Comment by George-du** [comment]
Hi Jonas,
     I'm looking forward to your reply. by the way, are graph-based pan-genomic strategies will be extended to multi-omics analysis?
    Best,
Du

**Comment by jonassibbesen** [comment]
Hi,

I am not able to replicate the error when using a compiled version of `rpvg`. I tried on both a mac and linux system. James, can you check that all the files are in the folder that you are running it from? This error could happen if `rpvg` can not find a file. I should probably add some more informative error messages if a file is not found. 

I am, however, able to replicate the error with the docker container. I do not know what the issue is yet. 

Best,

Jonas

**Comment by prenderj** [comment]
Hi Jonas

Thanks for getting back. I double checked was running in the right folder and seem to be:

![image](https://user-images.githubusercontent.com/8055834/157229022-651f9c67-288e-4042-aecb-9e1fe7117f6c.png)

I actually got the same error on two different computers.

**Comment by jonassibbesen** [comment]
I have recreated the docker container and it should now work. I am still not sure what happened with the old one. `rpvg` now completes on the example dataset without any problems:

```
docker run -it quay.io/jsibbesen/rpvg:latest
cd rpvg/example/
rpvg -t 4 -g graph.xg -p pantranscriptome.gbwt -f pantranscriptome.txt.gz -a mpmap_align.gamp -o rpvg --inference-model haplotype-transcripts
```
```
Running rpvg (commit: 0380bdb172bbe255a18ed070935fa0013dc02548)
Random number generator seed: 1647016967
Fragment length distribution parameters found in alignment (mean: 269.395, standard deviation: 44.4492)
Loaded graph, GBWT and r-index (0.958463 seconds, 1.09739 GB)
Fragment length distribution parameters re-estimated from alignment paths (location: 281.586, scale: 43.6241, shape: -0.167901)
Found alignment paths (5.32278 seconds, 1.09739 GB)
Clustered alignment paths (1.92169 seconds, 1.09739 GB)
Inferred path posterior probabilities and abundances (11.1969 seconds, 1.09739 GB)
```

Regarding your specific error James, I do not at the moment have any good ideas why this is happening. It has something to do with protobuf. What version of protobuf are you using?

**Comment by prenderj** [comment]
Hi Jonas

Thanks a lot. That is working for me now.

I think I may also have found the problem with the compiled version... I did a fresh install on AWS:

```
sudo apt install make cmake build-essential libz-dev protobuf-compiler libbz2-dev liblzma-dev libcurl4-openssl-dev pkg-config libjansson-dev

git clone --recursive https://github.com/jonassibbesen/rpvg.git
cd rpvg && mkdir build && cd build
cmake ..
make -j 2
```

And it worked and checking the input files they didn't match the size of the ones I had before, so sorry must have been an issue with these when copying them.

Thanks a lot for the help.
