### ISSUE TITLE
build rpvg failed

### ISSUE THREAD

**Issue by benjaminfang** [jonassibbesen/rpvg#40]
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Protobuf: /usr/lib64/libprotobuf.so (found version "3.19.4") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'htslib'
--   Found htslib, version 1.13
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fanghl/rpvg/build

===============================

[ 84%] Building CXX object CMakeFiles/rpvg-tests.dir/src/tests/main_test.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/fanghl/rpvg/deps/Catch2/single_include/catch2/catch.hpp:8034,
                 from /home/fanghl/rpvg/src/tests/main_test.cpp:4:
/home/fanghl/rpvg/deps/Catch2/single_include/catch2/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
/home/fanghl/rpvg/deps/Catch2/single_include/catch2/catch.hpp:10881:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10881 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/rpvg-tests.dir/build.make:76: CMakeFiles/rpvg-tests.dir/src/tests/main_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:256: CMakeFiles/rpvg-tests.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

===============================

I checkout Catch2 to v2.13.9 and the problem solved.

Hope this is helpful.

**Comment by jonassibbesen** [comment]
Hi, Thanks for letting me know. I just merged a PR that updates the Catch2 version used.
