### ISSUE TITLE
Could not install the rpvg in Linux

### ISSUE THREAD

**Issue by ld9866** [jonassibbesen/rpvg#44]
Dear developer:
We are trying to install your software, but we find it very difficult. I have installed it on two Linux servers separately, but I have encountered the same error.
When we print the cmake .. ,it showed all work well.
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Check for working C compiler: /home/user/anaconda3/bin/x86_64-conda-linux-gnu-cc
-- Check for working C compiler: /home/user/anaconda3/bin/x86_64-conda-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/user/anaconda3/bin/x86_64-conda-linux-gnu-c++
-- Check for working CXX compiler: /home/user/anaconda3/bin/x86_64-conda-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Protobuf: /home/user/anaconda3/lib/libprotobuf.so;-lpthread (found version "3.20.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'htslib'
--   Found htslib, version 1.14
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Software/rpvg/build

But when we tried to install, it showed below and l can not solve the problem well. Could you tell me what the problem is?

Protobuf will be /home/user/anaconda3/lib/libprotobuf.so;-pthread for PIC dynamic code and /home/user/anaconda3/lib/libprotobuf.so;-pthread for non-PIC static code
Using real Threads library
[ 21%] No build step for 'sdsl-lite-proj'
[ 23%] Performing install step for 'sdsl-lite-proj'
/bin/sh: 1: ./install.sh: Permission denied
make[2]: *** [CMakeFiles/sdsl-lite-proj.dir/build.make:74：sdsl-lite-proj-prefix/src/sdsl-lite-proj-stamp/sdsl-lite-proj-install] erro 126
make[1]: *** [CMakeFiles/Makefile2:255：CMakeFiles/sdsl-lite-proj.dir/all] erro 2
make[1]: *** 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Software/rpvg/deps/libvgio
[ 25%] Performing build step for 'libvgio-proj'
[ 19%] Built target handlegraph
[ 19%] Built target link_target
[ 59%] Built target vgio_static
[ 61%] Linking CXX shared library libvgio.so
[100%] Built target vgio
[ 26%] No install step for 'libvgio-proj'
[ 28%] Completed 'libvgio-proj'
[ 28%] Built target libvgio-proj
make: *** [Makefile:95：all]

**Comment by ld9866** [comment]
We also tried docker, but there were still some problems. We used the following code and the result showed 
Running rpvg (commit: 1282449273f3f39e75542cc751dd5f2630050a25)
Random number generator seed: 1677551317
rpvg: /home/rpvg/src/main.cpp:517: int main(int, char**): Assertion `frag_alignments_istream.is_open()' failed.

docker run --rm \
-v /home/user/Software/rpvg/example:/input \
quay.io/jsibbesen/rpvg:latest \
rpvg \
-t 4 -g input/graph.xg -p input/pantranscriptome.gbwt -f input/pantranscriptome.txt.gz -a input/mpmap_align.gamp -o input/rpvg --inference-model haplotype-transcripts

**Comment by jonassibbesen** [comment]
Hi, I am not sure why this is happening. It is the first time that I have seen this error. It looks like it could be something with your permissions. Do you have permissions to run the `./install.sh` file in the `deps/sdsl-lite/` folder?

**Comment by ld9866** [comment]
Hello developers!
Thank you for your enthusiastic reply, but we found it still difficult to install locally, I think this may be a problem on ubuntu, but we can run perfectly with docker, so it may not be a problem anymore.
