### ISSUE TITLE
Problems on pan-transcriptome index

### ISSUE THREAD

**Issue by LiuShang-777** [jonassibbesen/rpvg#49]
Hello,
Dear contributors,
I've prepared my files for pan-transcriptome building by vg autoindex using reference sequence, variations (SVs from other accessions) and gtf file generated from Stringtie. However, vg shows that only 3 file could not build index like this:

[vg autoindex] Excecuting command: vg autoindex --threads 8 --workflow mpmap --prefix test_A01 --ref-fasta A01.fa --vcf A01.vcf.gz --tx-gff A01.gtf
[IndexRegistry]: Checking for phasing in VCF(s).
[W::vcf_parse_info] INFO '.' is not defined in the header, assuming Type=String
error:[vg autoindex] Input is not sufficient to create indexes
Inputs
        GTF/GFF
        Reference FASTA
        VCF
are insufficient to create target index Haplotype-Transcript GBWT

There are 3 files which are consistent with examples given in vg autoindex illustration, I'm confused about the result that Inputs are insufficient to create index.
I'm looking forward for your helps.
Thanks for all contributors

**Comment by jeizenga** [comment]
Are you using an up-to-date version of VG? It looks like `vg autoindex` is attempting to produce the indexes for `rpvg` as well as `mpmap`, but these workflow pipelines have been separate options since v 1.45.0

**Comment by LiuShang-777** [comment]
> Are you using an up-to-date version of VG? It looks like `vg autoindex` is attempting to produce the indexes for `rpvg` as well as `mpmap`, but these workflow pipelines have been separate options since v 1.45.0

Thank you for your reply. 
vg version I used was v1.34.0. I have addressed this problem. The format of vcf file is incorrect. It should be like this:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
A01     1575    A01_1575     TATTAAAAAACCTAAAAAATTTAAATTACATTAAAGTTTTTTAAATTTATTTAATTTTAAAACAGTTGTTTCAAAATTAAACAGTTATGATC    T
       40      PASS    SVTYPE=INDEL;.  GT      1|1

The genotype information was "1/1" in my primitive vcf file which could not be recognized by vg

**Comment by jeizenga** [comment]
Yes, to make the haplotype-specific transcripts for `rpvg`, you need to have fully-specified haplotypes in the VCF, so a VCF with unphased variants can't be used.
