### ISSUE TITLE
'std::bad_alloc' error in rpvg

### ISSUE THREAD

**Issue by xuxingyubio** [jonassibbesen/rpvg#52]
I'm sorry to bother you.
I got the GWBT index followed by https://github.com/jonassibbesen/hprc-rnaseq-analyses-scripts/blob/main/graph_construction/minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32/index_gbwt.sh

When I use rpvg, I got an error like this: 
GBWT::load(): Invalid header: GBWT v5: 269821 sequences of total length 18863910, alphabet size 195633865 with offset 1115
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

What's going on here, how can I solve it?

**Comment by jonassibbesen** [comment]
Hi, thanks for writing. Are you able to share the command-lines you used for creating the GBWT index and run *rpvg*?

**Comment by xuxingyubio** [comment]
I have solved this problem. This issue is caused by the Docker container I previously used. Thank you for your reply.

**Comment by jonassibbesen** [comment]
Sounds good. I am going to close the issue. Please open it again if you run into the problem once more.
