### ISSUE TITLE
Can't run rpvg successfully

### ISSUE THREAD

**Issue by Tonitsk8264** [jonassibbesen/rpvg#54]
Running rpvg (commit: 1d91a9e379cb7b3f5260642ae1500d99b8afccf6)
Random number generator seed: 1693234232
Fragment length distribution parameters found in alignment (mean: 247.706, standard deviation: 55.7348)
Loaded graph and GBWT (7.87753 seconds, 3.51136 GB)
Fragment length distribution parameters re-estimated from alignment paths (location: 204.212, scale: 76.2045, shape: 1.94677)
Found alignment paths (769.318 seconds, 3.51136 GB)
Clustered alignment paths (369.159 seconds, 3.51136 GB)
rpvg: /psd/container/micromamba-0.25.1/envs/VG_v1.49.0/share/rpvg/src/main.cpp:317: spp::sparse_hash_map<std::__cxx11::basic_string<char>, PathInfo> parseHaplotypeTranscriptInfo(const string&, bool, bool): Assertion `haplotype_transcript_info_it.first->second.source_ids.emplace(haplotype_id_index_it.first->second).second' failed.

The above is the output log file of rpvg. I would like to understand where the error occurred.grateful
[rpvg.log](https://github.com/jonassibbesen/rpvg/files/12456555/rpvg.log)

**Comment by Tonitsk8264** [comment]
Name	Length	Transcripts	Haplotypes
MSTRG.1.1_R1	1810	MSTRG.1.1	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.2_R1	1993	MSTRG.1.2	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.3_R1	1685	MSTRG.1.3	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.4_R1	1792	MSTRG.1.4	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.5_R1	1380	MSTRG.1.5	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.10.1_R1	290	MSTRG.10.1	chr1,Sichuan#0#chr1,Sichuan#1#chr1,Chongqing#0#chr1
MSTRG.10.1_H1	290	MSTRG.10.1	Chongqing#1#chr1
MSTRG.10.1_H2	286	MSTRG.10.1	Hubei#0#chr1
MSTRG.10.1_H3	290	MSTRG.10.1	Hubei#1#chr1
MSTRG.100.1_R1	375	MSTRG.100.1	chr1,Sichuan#0#chr1
MSTRG.100.1_H1	375	MSTRG.100.1	Hubei#0#chr1
MSTRG.100.1_H2	375	MSTRG.100.1	Hubei#1#chr1
MSTRG.100.1_H3	375	MSTRG.100.1	Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#1#chr1
MSTRG.1000.1_R1	1294	MSTRG.1000.1	chr1
MSTRG.1000.1_H1	1290	MSTRG.1000.1	Hubei#0#chr1
MSTRG.1000.1_H2	1292	MSTRG.1000.1	Hubei#1#chr1
MSTRG.1000.1_H3	1294	MSTRG.1000.1	Chongqing#1#chr1,Sichuan#0#chr1
MSTRG.1000.1_H4	1294	MSTRG.1000.1	Sichuan#1#chr1
MSTRG.10000.1_R1	360	MSTRG.10000.1	chr2,Chongqing#0#chr2,Sichuan#1#chr2
MSTRG.10000.1_H1	360	MSTRG.10000.1	Chongqing#1#chr2
MSTRG.10000.1_H2	359	MSTRG.10000.1	Hubei#0#chr2
MSTRG.10000.1_H3	359	MSTRG.10000.1	Hubei#1#chr2
MSTRG.10000.1_H4	360	MSTRG.10000.1	Sichuan#0#chr2
MSTRG.10001.1_R1	280	MSTRG.10001.1	chr2,Chongqing#0#chr2,Sichuan#0#chr2,Sichuan#1#chr2
MSTRG.10001.1_H1	280	MSTRG.10001.1	Chongqing#1#chr2
MSTRG.10001.1_H2	279	MSTRG.10001.1	Hubei#0#chr2
MSTRG.10001.1_H3	278	MSTRG.10001.1	Hubei#1#chr2
MSTRG.10002.1_R1	572	MSTRG.10002.1	chr2,Chongqing#0#chr2,Sichuan#0#chr2,Sichuan#1#chr2
MSTRG.10002.1_H1	572	MSTRG.10002.1	Chongqing#1#chr2
MSTRG.10002.1_H2	572	MSTRG.10002.1	Hubei#0#chr2,Hubei#1#chr2
MSTRG.10002.2_R1	436	MSTRG.10002.2	chr2,Chongqing#0#chr2,Sichuan#0#chr2,Sichuan#1#chr2
MSTRG.10002.2_H1	436	MSTRG.10002.2	Chongqing#1#chr2
MSTRG.10002.2_H2	436	MSTRG.10002.2	Hubei#0#chr2,Hubei#1#chr2
MSTRG.10003.1_R1	2305	MSTRG.10003.1	chr2
MSTRG.10003.1_H1	2305	MSTRG.10003.1	Chongqing#0#chr2
MSTRG.10003.1_H2	2305	MSTRG.10003.1	Chongqing#1#chr2
MSTRG.10003.1_H3	2300	MSTRG.10003.1	Hubei#0#chr2
MSTRG.10003.1_H4	2300	MSTRG.10003.1	Hubei#1#chr2
MSTRG.10003.2_R1	2176	MSTRG.10003.2	chr2
MSTRG.10003.2_H1	2176	MSTRG.10003.2	Chongqing#0#chr2
MSTRG.10003.2_H2	2176	MSTRG.10003.2	Chongqing#1#chr2
MSTRG.10003.2_H3	2171	MSTRG.10003.2	Hubei#0#chr2
MSTRG.10003.2_H4	2171	MSTRG.10003.2	Hubei#1#chr2
MSTRG.10004.1_R1	385	MSTRG.10004.1	chr2,Sichuan#1#chr2
MSTRG.10004.1_H1	385	MSTRG.10004.1	Chongqing#0#chr2,Chongqing#1#chr2
MSTRG.10004.1_H2	380	MSTRG.10004.1	Hubei#0#chr2
MSTRG.10004.1_H3	384	MSTRG.10004.1	Hubei#1#chr2
MSTRG.10004.1_H4	385	MSTRG.10004.1	Sichuan#0#chr2

It seems that there is something wrong with my txt file, can you help me? grateful

**Comment by Tonitsk8264** [comment]
```Name	Length	Transcripts	Haplotypes
MSTRG.1.1_R1	1810	MSTRG.1.1	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.2_R1	1993	MSTRG.1.2	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.3_R1	1685	MSTRG.1.3	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.4_R1	1792	MSTRG.1.4	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.5_R1	1380	MSTRG.1.5	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.10.1_R1	290	MSTRG.10.1	chr1,Sichuan#0#chr1,Sichuan#1#chr1,Chongqing#0#chr1
MSTRG.10.1_H1	290	MSTRG.10.1	Chongqing#1#chr1
MSTRG.10.1_H2	286	MSTRG.10.1	Hubei#0#chr1
MSTRG.10.1_H3	290	MSTRG.10.1	Hubei#1#chr1
MSTRG.100.1_R1	375	MSTRG.100.1	chr1,Sichuan#0#chr1
MSTRG.100.1_H1	375	MSTRG.100.1	Hubei#0#chr1
MSTRG.100.1_H2	375	MSTRG.100.1	Hubei#1#chr1
MSTRG.100.1_H3	375	MSTRG.100.1	Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#1#chr1
MSTRG.1000.1_R1	1294	MSTRG.1000.1	chr1
MSTRG.1000.1_H1	1290	MSTRG.1000.1	Hubei#0#chr1
MSTRG.1000.1_H2	1292	MSTRG.1000.1	Hubei#1#chr1
MSTRG.1000.1_H3	1294	MSTRG.1000.1	Chongqing#1#chr1,Sichuan#0#chr1
MSTRG.1000.1_H4	1294	MSTRG.1000.1	Sichuan#1#chr1```

It seems that there is something wrong with my txt file, can you help me? grateful

**Comment by Tonitsk8264** [comment]
```Name	Length	Transcripts	Haplotypes
MSTRG.1.1_R1	1810	MSTRG.1.1	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.2_R1	1993	MSTRG.1.2	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.3_R1	1685	MSTRG.1.3	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.4_R1	1792	MSTRG.1.4	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.5_R1	1380	MSTRG.1.5	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.10.1_R1	290	MSTRG.10.1	chr1,Sichuan#0#chr1,Sichuan#1#chr1,Chongqing#0#chr1
MSTRG.10.1_H1	290	MSTRG.10.1	Chongqing#1#chr1
MSTRG.10.1_H2	286	MSTRG.10.1	Hubei#0#chr1
MSTRG.10.1_H3	290	MSTRG.10.1	Hubei#1#chr1
MSTRG.100.1_R1	375	MSTRG.100.1	chr1,Sichuan#0#chr1
MSTRG.100.1_H1	375	MSTRG.100.1	Hubei#0#chr1
MSTRG.100.1_H2	375	MSTRG.100.1	Hubei#1#chr1
MSTRG.100.1_H3	375	MSTRG.100.1	Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#1#chr1
MSTRG.1000.1_R1	1294	MSTRG.1000.1	chr1
MSTRG.1000.1_H1	1290	MSTRG.1000.1	Hubei#0#chr1
MSTRG.1000.1_H2	1292	MSTRG.1000.1	Hubei#1#chr1
MSTRG.1000.1_H3	1294	MSTRG.1000.1	Chongqing#1#chr1,Sichuan#0#chr1
MSTRG.1000.1_H4	1294	MSTRG.1000.1	Sichuan#1#chr1```

It seems that there is something wrong with my txt file, can you help me? grateful

**Comment by Tonitsk8264** [comment]
```
Name	Length	Transcripts	Haplotypes
MSTRG.1.1_R1	1810	MSTRG.1.1	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.2_R1	1993	MSTRG.1.2	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.3_R1	1685	MSTRG.1.3	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.4_R1	1792	MSTRG.1.4	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.5_R1	1380	MSTRG.1.5	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.10.1_R1	290	MSTRG.10.1	chr1,Sichuan#0#chr1,Sichuan#1#chr1,Chongqing#0#chr1
MSTRG.10.1_H1	290	MSTRG.10.1	Chongqing#1#chr1
MSTRG.10.1_H2	286	MSTRG.10.1	Hubei#0#chr1
MSTRG.10.1_H3	290	MSTRG.10.1	Hubei#1#chr1
MSTRG.100.1_R1	375	MSTRG.100.1	chr1,Sichuan#0#chr1
MSTRG.100.1_H1	375	MSTRG.100.1	Hubei#0#chr1
MSTRG.100.1_H2	375	MSTRG.100.1	Hubei#1#chr1
MSTRG.100.1_H3	375	MSTRG.100.1	Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#1#chr1
MSTRG.1000.1_R1	1294	MSTRG.1000.1	chr1
MSTRG.1000.1_H1	1290	MSTRG.1000.1	Hubei#0#chr1
MSTRG.1000.1_H2	1292	MSTRG.1000.1	Hubei#1#chr1
MSTRG.1000.1_H3	1294	MSTRG.1000.1	Chongqing#1#chr1,Sichuan#0#chr1
MSTRG.1000.1_H4	1294	MSTRG.1000.1	Sichuan#1#chr1
```

It seems that there is something wrong with my txt file, can you help me? grateful

**Comment by Tonitsk8264** [comment]
It seems that there is something wrong with my txt file, can you help me? grateful
pantranscriptome.txt
```
Name	Length	Transcripts	Haplotypes
MSTRG.1.1_R1	1810	MSTRG.1.1	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.2_R1	1993	MSTRG.1.2	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.3_R1	1685	MSTRG.1.3	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.4_R1	1792	MSTRG.1.4	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.1.5_R1	1380	MSTRG.1.5	chr1,Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#0#chr1,Sichuan#1#chr1
MSTRG.10.1_R1	290	MSTRG.10.1	chr1,Sichuan#0#chr1,Sichuan#1#chr1,Chongqing#0#chr1
MSTRG.10.1_H1	290	MSTRG.10.1	Chongqing#1#chr1
MSTRG.10.1_H2	286	MSTRG.10.1	Hubei#0#chr1
MSTRG.10.1_H3	290	MSTRG.10.1	Hubei#1#chr1
MSTRG.100.1_R1	375	MSTRG.100.1	chr1,Sichuan#0#chr1
MSTRG.100.1_H1	375	MSTRG.100.1	Hubei#0#chr1
MSTRG.100.1_H2	375	MSTRG.100.1	Hubei#1#chr1
MSTRG.100.1_H3	375	MSTRG.100.1	Chongqing#0#chr1,Chongqing#1#chr1,Sichuan#1#chr1
MSTRG.1000.1_R1	1294	MSTRG.1000.1	chr1
MSTRG.1000.1_H1	1290	MSTRG.1000.1	Hubei#0#chr1
MSTRG.1000.1_H2	1292	MSTRG.1000.1	Hubei#1#chr1
MSTRG.1000.1_H3	1294	MSTRG.1000.1	Chongqing#1#chr1,Sichuan#0#chr1
MSTRG.1000.1_H4	1294	MSTRG.1000.1	Sichuan#1#chr1
```

gtf
```
# stringtie --merge -p 8 -o Sichuan.merged.gtf list/Sichuan.list        # stringtie --merge -p 8 -o Sichuan.merged.gtf list/Sichuan.list
# StringTie version 2.2.1       # StringTie version 2.2.1
chr1    StringTie       transcript      26941   30003   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1";
chr1    StringTie       exon    26941   27581   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "1";
chr1    StringTie       exon    27740   27924   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "2";
chr1    StringTie       exon    28345   28741   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "3";
chr1    StringTie       exon    29346   29505   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "4";
chr1    StringTie       exon    29577   30003   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "5";
chr1    StringTie       transcript      27144   30003   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.2";
chr1    StringTie       exon    27144   27924   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.2"; exon_number "1";
chr1    StringTie       exon    28117   28741   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.2"; exon_number "2";
chr1    StringTie       exon    29346   29505   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.2"; exon_number "3";
chr1    StringTie       exon    29577   30003   1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.2"; exon_number "4";
```

vcf
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sichuan Chongqing       Hubei
chr1    80      .       C       CA      23.68   PASS    ORP=71;ORL=10   GT:GQ:PS        1|0:23.5:876    0/0:.:. 0/0:.:.
chr1    150     .       A       C       22.032  PASS    PR=0.0065,0.9937,0.0025,0.0049;FQ=0.6316        GT:DP:VF:AD:ADF:ADR:PS  0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.   1/1:38:0.6316:9,24:2,6:7,18:.
chr1    349     .       G       A       15.374  PASS    PR=0.971,0.0018,0.05,0.002;FQ=0.7       GT:DP:VF:AD:ADF:ADR:PS  0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.   1/1:40:0.7:11,28:5,6:6,22:.
chr1    497     .       G       A       23.222  PASS    PR=0.9952,0.0016,0.0072,0.0017;FQ=0.7857        GT:DP:VF:AD:ADF:ADR:PS  0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.   1/1:42:0.7857:2,33:2,10:0,23:.
chr1    731     .       T       C       12.395  PASS    PR=0.0025,0.9424,0.0039,0.0668;FQ=0.4186        GT:DP:VF:AD:ADF:ADR:PS  0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.   1/1:43:0.4186:10,18:0,5:10,13:.
chr1    749     .       TTTTAAAAAAA     T       20.4    PASS    ORP=742;ORL=21  GT:GQ:PS        1|0:9.15:876    0/0:.:. 0/0:.:.
chr1    847     .       T       C       24.481  PASS    PR=0.0002,0.9964,0.0003,0.0049;FQ=0.6875        GT:DP:VF:AD:ADF:ADR:PS  1/1:32:0.6875:7,22:4,12:3,10:.    0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.
chr1    876     .       G       A       19.573  PASS    PR=0.989,0.0011,0.9928,0.0006;FQ=0.2581 GT:DP:VF:AD:ADF:ADR:PS  0|1:31:0.2581:20,8:9,4:11,4:876   0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.
chr1    988     .       T       A       14.851  PASS    PR=0.9673,0.0022,0.0018,0.99;FQ=0.3333  GT:DP:VF:AD:ADF:ADR:PS  0|1:30:0.3333:17,10:7,5:10,5:876  0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.
chr1    1012    .       T       C       12.498  PASS    PR=0.0015,0.9437,0.0009,0.9981;FQ=0.3   GT:DP:VF:AD:ADF:ADR:PS  0|1:30:0.3:17,9:9,5:8,4:876       0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.
chr1    1044    .       A       C       21.38   PASS    PR=0.9927,0.993,0.0008,0.0011;FQ=0.3333 GT:DP:VF:AD:ADF:ADR:PS  0|1:30:0.3333:20,10:9,6:11,4:876  1/1:30:0.4667:16,14:7,7:9,7:.   1/1:43:0.5116:16,22:5,6:11,16:.
chr1    1086    .       A       G       26.417  PASS    PR=0.0005,0.0005,0.9977,0.0003;FQ=0.7667        GT:DP:VF:AD:ADF:ADR:PS  1/1:30:0.7667:3,23:1,11:2,12:.    1/1:29:0.7931:4,23:3,9:1,14:.   1/1:44:0.5909:7,26:3,11:4,15:.
chr1    1173    .       G       T       11.111  PASS    PR=0.0019,0.0015,0.9975,0.9226;FQ=0.1935        GT:DP:VF:AD:ADF:ADR:PS  0|1:31:0.1935:21,6:10,2:11,4:876  0/0:.:.:.:.:.:. 0/0:.:.:.:.:.:.
```

**Comment by jeizenga** [comment]
Based on the logging info, it looks to me like you have a duplicate haplotype transcript somewhere in the path info file (supplied with `--path-info` or `-f`). Could you either confirm that this is the case, or else provide the file you used for us to check?

**Comment by Tonitsk8264** [comment]
Thank you for your help. Please inform me if there are other documents I need to provide. Thanks once again.
[Uploading pantranscriptome.zip…]()

**Comment by Tonitsk8264** [comment]
Sorry I replied in the wrong place, here is my txt file, please check it for me, thanks. Meanwhile the vcf and gtf files have been emailed to you. @jeizenga 
[pantranscriptome.zip](https://github.com/jonassibbesen/rpvg/files/12588644/pantranscriptome.zip)

**Comment by Tonitsk8264** [comment]
Sorry to bother you again, I will follow [https://github.com/jonassibbesen/vgrna-project-paper/tree/main/scripts/bash/contruct_pantranscriptome](https://github.com/jonassibbesen/vgrna-project-paper/tree/main/scripts/bash/contruct_pantranscriptome) The command on the website to rebuild the index still encountered the same issue when running rpvg

**Comment by jjuhyunkim** [comment]
I had the same issue. I removed all the duplicated haplotypes in the 4th column, but `rpvg` produced the same error again. Could you please let me know what your guidance has uncovered so far? Is there anything I can do about this matter that would be helpful to you? This is my text file. 

[output.txt.gz](https://github.com/jonassibbesen/rpvg/files/13272744/output.txt.gz)

**Comment by jeizenga** [comment]
Sorry for the significantly delayed solution, but I believe I have resolved this problem, which actually occurs upstream in `vg rna` with this PR: https://github.com/vgteam/vg/pull/4156.

In investigating your data, it seemed to me that you have relatively short phase blocks in your VCF. Is that expected? If so, then you may continue to encounter some issues with `vg rna` and `rpvg`. Because they both work with haplotype-resolved transcripts, your phase blocks should be at least as long as a typical transcript (often 10s-100s kbp). Otherwise, many haplotype-specific transcripts will be dropped from the analysis, because `vg rna` will not be able to project the entire transcript onto the haplotype. There are also some technical issues that we have not yet resolved, which you can see discussed in the comments of that PR.

I'm going to resolve this issue, but please let me know if it should be re-opened.
