### ISSUE TITLE
Meaning of input and output files of pantranscriptome

### ISSUE THREAD

**Issue by dongdongdong0203** [jonassibbesen/rpvg#55]
Hi, developer,
 I have some confusion about rpvg input and output files and would like to get answers from you guys!
First, I ran vg autoindex:
```
vg autoindex \
--threads 32 \
--workflow mpmap \
--workflow rpvg \
--prefix chr1 \
--ref-fasta ./3.fasta/Sus_scrofa.Sscrofa11.1.chr1.dna.toplevel.fa \
--vcf .1.SNP/103ind_tran_chr1_qc.generegion.phased.vcf.gz \
--tx-gff ./4.gtf/Sus_scrofa.Sscrofa11.1.100.chr1.gtf
```

Then, I ran in vg mpmap and rpvg:
```
time vg mpmap \
--nt-type rna \
--threads 32 \
--graph-name ${autoindex}/chr1.spliced.xg \
--gcsa-name ${autoindex}/chr1.spliced.gcsa \
--dist-name ${autoindex}/chr1.spliced.dist \
--fastq ${rnapath}/${rnaseq[$SLURM_ARRAY_TASK_ID]}_1.qc.fq.gz \
--fastq ${rnapath}/${rnaseq[$SLURM_ARRAY_TASK_ID]}_2.qc.fq.gz \
> ${quanti}/${rnaseq[$SLURM_ARRAY_TASK_ID]}.mpmap.gamp


time rpvg \
-t 32 \
--graph ${autoindex}/chr1.spliced.xg \
--paths ${autoindex}/chr1.haplotx.gbwt \
--path-info ${autoindex}/chr1.txorigin.tsv \
--alignments ${quanti}/${rnaseq[$SLURM_ARRAY_TASK_ID]}.mpmap.gamp \
--inference-model haplotype-transcripts \
--output-prefix ${quanti}/${rnaseq[$SLURM_ARRAY_TASK_ID]}.rpvg 
```
My questions:
(1) In the first column in the txorgin.tsv file, I found that each transcript has either "_R" or "_H" added after the original transcript ID. however, the R is usually only R1, and the H has a different number. May I ask what R and H denote？
```
ENSSSCT00000004431_R1   2699    ENSSSCT00000004431      1
ENSSSCT00000004431_H1   2699    ENSSSCT00000004431      20D006138_20D006138#0#1,20D006316_20D006316#0#1,20D006539_20D006539#0#1,20D006539_20D006539#1#1,20D006565_20D006565#1#1,20D006753_20D
ENSSSCT00000004431_H2   2699    ENSSSCT00000004431      20D006138_20D006138#1#1,20D006191_20D006191#0#1,20D006191_20D006191#1#1,20D006202_20D006202#0#1,20D006202_20D006202#1#1,20D006228_20D
ENSSSCT00000004431_H3   2699    ENSSSCT00000004431      20D006140_20D006140#0#1
ENSSSCT00000004431_H4   2699    ENSSSCT00000004431      20D006140_20D006140#1#1
ENSSSCT00000004431_H5   2699    ENSSSCT00000004431      20D006170_20D006170#0#1
ENSSSCT00000004431_H6   2699    ENSSSCT00000004431      20D006170_20D006170#1#1
ENSSSCT00000004431_H7   2699    ENSSSCT00000004431      20D006176_20D006176#0#1,20D006348_20D006348#0#1
ENSSSCT00000004431_H8   2699    ENSSSCT00000004431      20D006176_20D006176#1#1,20D006944_20D006944#0#1
```

(2) What is the meaning of the number between the two "#" in the "sample ID#0# chromosome number" in the "haplotype" column contained in the txorgin.tsv file generated by vg autoindex? Like ` 20D006140_20D006140#0#1`

(3) The rpvg_joint.txt file contains the second column "." .What is the cause of this
```
ENSSSCT00000080639_H5   .       525     1       99.141873       41.252798       0       0
ENSSSCT00000004553_H5   .       158     0.80520778      2.6734957       0.48751255      0       0
ENSSSCT00000004553_H13  .       158     0.16104156      0.53469914      0.097502509     0       0
ENSSSCT00000004553_H8   .       158     0.0033411062    0       0       0       0
ENSSSCT00000025290_R1   .       82      1       185.37403       94.535129       0       0
ENSSSCT00000005985_H8   .       336     0.79019431      0       0       0       0
ENSSSCT00000005985_R1   .       336     0.20509095      0       0       0       0
ENSSSCT00000005985_H28  .       336     0.0047147401    0       0       0       0
```
Looking forward to your answers and replies.

Thanks

**Comment by jeizenga** [comment]
1) The "R" indicates a reference transcript that was provided directly from the GTF, and "H" indicates a reference transcript that was projected onto a haplotype.
2) The "#" are used according to the [VG path metadata model](https://github.com/vgteam/vg/wiki/Path-Metadata-Model), in which they indicate the haplotype and the chromosome respectively.
3) I'm less sure about this point, but I believe that column is the "Cluster", right? There should be a header line printed at the top of this file. Two transcripts are included in the same cluster if there's any alignment that maps to both of them (typically because they share an exon). It's essentially a data-driven way to define genes. My guess is that "." means there were no reads mapped to that transcript, so it didn't get a cluster assignment.

**Comment by dongdongdong0203** [comment]
Thank you for your prompt response @jeizenga.
For the third question, I'm very sorry I didn't provide the full header information. Here is joint_rpvg.txt with header information, where ". " is the Name2 column, not the cluster column. 
```
Name_1	Name_2	ClusterID	HaplotypingProbability	ReadCount_1	TPM_1	ReadCount_2	TPM_2
ENSSSCT00000080639_H5	.	525	1	99.141873	41.252798	0	0
ENSSSCT00000004553_H5	.	158	0.80520778	2.6734957	0.48751255	0	0
ENSSSCT00000004553_H13	.	158	0.16104156	0.53469914	0.097502509	0	0
ENSSSCT00000004553_H8	.	158	0.0033411062	0	0	0	0
ENSSSCT00000025290_R1	.	82	1	185.37403	94.535129	0	0
ENSSSCT00000005985_H8	.	336	0.79019431	0	0	0	0
ENSSSCT00000005985_R1	.	336	0.20509095	0	0	0	0
ENSSSCT00000005985_H28	.	336	0.0047147401	0	0	0	0
ENSSSCT00000090647_H6	.	1067	0.0057650531	0.0057738029	0.00089982891	0	0
ENSSSCT00000090647_H27	.	1067	0.0057650531	0.0057738029	0.00089982891	0	0
```
In my tests with real data, joint_rpvg.txt exists with 40 rows of such results, however I don't understand the Name2 column appearing as ". ".

In addition, the time required to run `vp mpmap` is very long, a 270Mb chromosome takes 5 days longer than RNA-seq with 6G base amounts, and the number of haplotype transcripts does not affect the speed of the run. Do you have any better suggestions for this? I have a lot of RNA-seq data to mapping via `vg mpmap` in the future!

Looking forward to your answers and replies.

Thanks

**Comment by dongdongdong0203** [comment]
> 1. The "R" indicates a reference transcript that was provided directly from the GTF, and "H" indicates a reference transcript that was projected onto a haplotype.
> 2. The "#" are used according to the [VG path metadata model](https://github.com/vgteam/vg/wiki/Path-Metadata-Model), in which they indicate the haplotype and the chromosome respectively.
> 3. I'm less sure about this point, but I believe that column is the "Cluster", right? There should be a header line printed at the top of this file. Two transcripts are included in the same cluster if there's any alignment that maps to both of them (typically because they share an exon). It's essentially a data-driven way to define genes. My guess is that "." means there were no reads mapped to that transcript, so it didn't get a cluster assignment.

Thank you for your prompt response @jeizenga.
For the third question, I'm very sorry I didn't provide the full header information. Here is joint_rpvg.txt with header information, where ". " is the Name2 column, not the cluster column. 
```
Name_1	Name_2	ClusterID	HaplotypingProbability	ReadCount_1	TPM_1	ReadCount_2	TPM_2
ENSSSCT00000080639_H5	.	525	1	99.141873	41.252798	0	0
ENSSSCT00000004553_H5	.	158	0.80520778	2.6734957	0.48751255	0	0
ENSSSCT00000004553_H13	.	158	0.16104156	0.53469914	0.097502509	0	0
ENSSSCT00000004553_H8	.	158	0.0033411062	0	0	0	0
ENSSSCT00000025290_R1	.	82	1	185.37403	94.535129	0	0
ENSSSCT00000005985_H8	.	336	0.79019431	0	0	0	0
ENSSSCT00000005985_R1	.	336	0.20509095	0	0	0	0
ENSSSCT00000005985_H28	.	336	0.0047147401	0	0	0	0
ENSSSCT00000090647_H6	.	1067	0.0057650531	0.0057738029	0.00089982891	0	0
ENSSSCT00000090647_H27	.	1067	0.0057650531	0.0057738029	0.00089982891	0	0
```
In my tests with real data, joint_rpvg.txt exists with 40 rows of such results, however I don't understand the Name2 column appearing as ". ".

In addition, the time required to run `vp mpmap` is very long, a 270Mb chromosome takes 5 days longer than RNA-seq with 6G base amounts, and the number of haplotype transcripts does not affect the speed of the run. Do you have any better suggestions for this? I have a lot of RNA-seq data to mapping via `vg mpmap` in the future!

Looking forward to your answers and replies.

Thanks

**Comment by jeizenga** [comment]
Ah, thank you, that helps. I'm pretty sure the "." for Name2 means that the transcript is homozygous in that row (i.e. there are no variants distinguishing the 2 haplotypes within the coding exonic regions).

**Comment by dongdongdong0203** [comment]
Thank you so much for your enthusiastic response and for providing such an AMAZING software, rpvg!

**Comment by dongdongdong0203** [comment]
Thank you so much for your enthusiastic response and for providing such an AMAZING software, rpvg!

**Comment by jonassibbesen** [comment]
Hi, just wanted to clarify the meaning of the "." in the _Name2_ column. The "." represents that there is no HST version of the transcript for one of the haplotypes in the inferred diplotype. This can happen if it was not possible to project (liftover) a transcript on to a spcific haplotype due to for example an indel at an exon boundary.

**Comment by yeeus** [comment]
> In addition, the time required to run vp mpmap is very long, a 270Mb chromosome takes 5 days longer than RNA-seq with 6G base amounts, and the number of haplotype transcripts does not affect the speed of the run. Do you have any better suggestions for this? I have a lot of RNA-seq data to mapping via vg mpmap in the future!
I also met this problem. It took me much time to run `vg mpmap`, do you have any methods to speed up @jeizenga @jonassibbesen @dongdongdong0203 ?
Wish your help! Thanks very much!
